project:
  type: website

website:
  title: "MEF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - publications.qmd
      - Teaching.qmd
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



