project:
  type: website

website:
  title: "MEF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - href: publications/index.qmd
        text: Publications      
      - Teaching.qmd
      - text: Publications
        href: publicationscan.qmd
      - href: about/about.qmd
        text: About
format:
  html:
    theme: cerulean
    css: styles.css
    lang: en
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'

    toc: true



