project:
  type: website

website:
  title: "MEF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - href: publications/index.qmd
        text: Publications      
      - Teaching.qmd
      - href: about/about.qmd
        text: About
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



