---
title: "Research"
---

## Decision making under threat

I am interested in how stress, danger, and negativity biases influence cognitive, emotional and  decision-making processes of individuals and groups when facing various large-scale threats (e.g., such as terrorism, financial crises, climate change, pandemics, crime, and police threats). Specifically, I focus on understanding why individuals with different ideological belief systems, including those on the left and right of the spectrum, either "close off" by favoring exclusionary, security-focused, and risk-averse measures or "reach out" by prioritizing liberty-focused, collaborative, and inclusionary responses to threats.

Divergent responses to threats not only deepen interpersonal and intergroup polarization and conflict but also decrease willingness to compromise, potentially promoting anti-democratic behaviors. My research also explores how perception of shared threats and challenges can foster cooperation and reduce polarization when individuals and groups unite around common goals and engage in inclusive dialogue to enhance cooperation.

By uncovering how political beliefs shape perceptions of threats and subsequent responses, my research aims to inform strategies that promote understanding, dialogue, and resilience in democratic societies facing complex challenges. 



<!--
I employ a variety of methods (e.g. surveys, lab experiments etc.) to investigate the cognitive, biological and economic foundations of socio-political attitudes and beliefs. Here are some of my interests

Political ideology and intergroup relations

This area of study seeks to understand how political beliefs and values influence interactions between different social, ethnic, and political groups, as well as the consequences of these interactions for social cohesion and conflict. 

## Threat perception, risk-taking and negativity bias
This area seeks to understand how threat perception, risk-taking and negativity bias shape human behavior, with a particular focus on the broad applications for understanding intergroup relations, anti-democratic behaviors, and political beliefs. 

## The antecedents and consequences of conspiracy beliefs

This area of study seeks to understand the factors that lead individuals to adopt conspiracy theories and the impacts these beliefs have on behavior and society.


## In the news
-->



